from enum import Enum

class EventType(Enum):
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    DATA_UPDATE = "DATA_UPDATE"
    SYSTEM_ALERT = "SYSTEM_ALERT"
    ITEM_CREATED = "ITEM_CREATED"
    ITEM_DELETED = "ITEM_DELETED"
    CUSTOM_EVENT = "CUSTOM_EVENT"
